### ISSUE TITLE
Add new landing page repo as a transition while we keep the current landing page up

### ISSUE THREAD

**Issue by GuiBibeau** [AkeruAI/akeru#106]
We are starting to migrate to a new landing page with a new design language. During this time we should keep the current landing page code in it's current place to have continuity and have access to the code. Things like  the waiting list forms and logic can be reused.

Acceptance criteria:

- implement the new TS repo from the studio template, ask @GuiBibeau for the zip file
- update the readme to the akeru-frontend package to mention we are deprecating that code base
- remove any mentions of tailwind UI in the new package and readme to make sure we are not confusing people as to why this package exists.
- work with Gui to host on vercel a temporary build to see changes progressively
- make sure the readme of the new package stipulates this is a transtion.

**Comment by tobySolutions** [comment]
Okay, I'm down for this @GuiBibeau; how do we start?

**Comment by GuiBibeau** [comment]
Should be pretty well detailed! I'll send you the zip in chat

**Comment by tobySolutions** [comment]
> Should be pretty well detailed! I'll send you the zip in chat

Ok, awesome!! Thank you very much Gui. I'll take a crack at it.

**Comment by tobySolutions** [comment]
Fixed #115
