### ISSUE TITLE
Clean up OOP patterns in validator and cloudflare-miner

### ISSUE THREAD

**Issue by GuiBibeau** [AkeruAI/akeru#43]
As left overs from the subnet template we have inherited a lot of technical dept of a coding style that is far from our own. Let's clean up the OOP patterns. We can keep some of them but inheritance is overly done for our style and offuscates the real functionalities of the code. Let's move closer to a functional style

**Comment by multipletwigs** [comment]
Since we're no longer working on bittensor related models, we will be closing this issue!
