### ISSUE TITLE
Create a contributing guide

### ISSUE THREAD

**Issue by GuiBibeau** [AkeruAI/akeru#63]
Since adding the subnet to the project, contributing can mean different things. We will start to have contributors to only the UI, only the API, only the subnet or even contributors who want to run the full project from end to end. We need better documentation and guides on how to get started contributing.

**Acceptance Criteria**:

- [ ] Build a contributing section for the UI.
- [ ] Build a contributing section for the API.
- [ ] Build a contributing section for validator and miner code.
- [ ] Host all sections on the contributing page.

**Comment by tobySolutions** [comment]
> only the subnet or even contributors who want to run the full project from end to end. We need better docs and guides on how to get started contributing:

This looks good to me! I can work this when it's due to start.
