### ISSUE TITLE
Move args from subnet packages to environment variables instead.

### ISSUE THREAD

**Issue by GuiBibeau** [AkeruAI/akeru#71]
As a left over from the subnet template, most configurations options are passed from command line arguments. For easier deployments and decoupling from the validator and miner classes, let's move them into env files instead.

**Comment by tobySolutions** [comment]
> As a left over from the subnet template, most configurations options are passed from command line arguments. For easier deployments and decoupling from the validator and miner classes, let's move them into env files instead.

Great idea, actually!!
