### ISSUE TITLE
In readme `here` link is not clickable

### ISSUE THREAD

**Issue by subhamkumarr** [AkeruAI/akeru#79]
# Description:
In the readme file See the full Contributing guide `here`  here link is not clickable

**Comment by subhamkumarr** [comment]
@GuiBibeau  is this a valid issue?

**Comment by TommieTechie** [comment]
Hi @subhamkumarr, I wanted to let you know that the issue you raised should have been resolved as part of #101. Thanks for letting us know about that, and if you got any questions, please don't hesitate to reach out.
